server:
  port: 8087

spring:
  application:
    name: Multithreaded-Batched-Processing

  datasource:
    url: jdbc:h2:mem:product-csv-db-batch-processing
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 1000              # ✅ Enables JDBC batching
          batch_versioned_data: true    # ✅ Supports versioned entities in batch
        order_inserts: true             # ✅ Orders INSERTs to optimize batching
        order_updates: true             # ✅ Orders UPDATEs to optimize batching
        generate_statistics: true       # ✅ Enables Session Metrics logs

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.engine.jdbc.batch.internal: DEBUG
